package dk.nikolajbrinch.assembler.wdc65c02;

public enum AddressingMode {
  UNKNOWN,

  ABSOLUTE,
  ABSOLUTE_INDEXED_INDIRECT,
  ABSOLUTE_INDEXED,
  ABSOLUTE_INDIRECT,
  ACCUMULATOR,
  IMMEDIATE,
  IMPLIED,
  RELATIVE,
  STACK,
  ZERO_PAGE,
  ZERO_PAGE_INDEXED_INDIRECT,
  ZERO_PAGE_INDEXER,
  ZERO_PAGE_INDIRECT,
  ZERO_PAGE_INDIRECT_INDEXED;
}
